### PR TITLE
Allow browser+CDN caching of OPTIONS responses with appropriate Vary settings

### PR DESCRIPTION
**Pull request by rowanbeentje**
I noticed quite a few OPTIONS requests mixed in with spoor-api requests, and am pretty sure these can safely be made cacheable.  The only issue might be if `Vary` headers will be trampled by downstream/CDN - could that be the case?

Seems to improve the situation a lot locally; Chrome caps caching to 10 mins, I think, but the CDN should cache beyond that.

### CODE REVIEW

**Comment by commuterjoy** [comment]
We did try this & I'm just trying to remember why we rolled it back... 

/cc @wheresrhys

**Comment by rowanbeentje** [comment]
Was that https://github.com/Financial-Times/spoor-api/commit/6e6f644ee385e032cbe52a030cf9c03ef568a188 ?

**Comment by commuterjoy** [comment]
yes

**Comment by commuterjoy** [comment]
https://financialtimes.slack.com/archives/spoor/p1465461279000015

**Comment by rowanbeentje** [comment]
Hmm.  So that was on all requests with an Origin, but only modified the Access-Control-Max-Age header - very strange...

I don't quite follow the reasoning on the POST/OPTIONS bodyweight issue mentioned in the archived chat - think it was aborting the request because it decided CORS wasn't permitted after all?  If so, potentially having only the OPTIONS request cached (as opposed to setting the header on all CORS requests but still not allowing caching of the OPTIONS) will change the behaviour?

**Comment by commuterjoy** [comment]
Our theory was OPTIONS requests were cached, therefore the larger POST request was being sent sooner than it otherwise would of bean, and the page unloading was terminating the client request, which is why we saw a spike in fastly errors.

A little bit of speculation as we didn't do further research.

**Comment by commuterjoy** [comment]
(i don't mind trying this again btw)

**Comment by wheresrhys** [comment]
> would of bean
:joy:

I say lets try it. If we don't see a decrease in spoor events going in to the queue it's probably ok, no?

**Comment by rowanbeentje** [comment]
Gotcha on the requests being terminated - so if we see the same failures at the same time as an *increase* in tracking requests, that would explain it.

I also vote try it again - but wouldn't know what to monitor for an eye to roll back - happy to do this if someone sets me up on the appropriate systems, happier to defer to either of you two :)

**Comment by commuterjoy** [comment]
> queue it's probably ok

yes, apart from the extra error noise.

> what to monitor

http://grafana.ft.com/dashboard/db/spoor-radiator - there's a couple of Fastly graphs.

**Pull request merged**
